install! 'cocoapods',
  :generate_multiple_pod_projects => true,
  :incremental_installation => true

workspace 'ExamplePod.xcworkspace'
project 'Example/Example.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ExamplePod' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example
 pod 'SnapKit'
 pod 'DVTUIKit', :path => '../DVTUIKit'
 pod 'DVTObjectMapper', :path => '../DVTObjectMapper'
 pod 'DVTNetwork', :path => '../DVTNetwork'
 pod 'DVTLoger', :path => '../DVTLoger'
 pod 'DVTFoundation', :path => '../DVTFoundation'
 pod 'DVTSecurity', :path => '../DVTSecurity'
 pod 'DVTScan', :path => '../DVTScan'
end
